# Defaults
defaults:
  - scope:
      path: 'content/_help/**/*'
    values:
      layout: help
  - scope:
      path: 'content/_policy/*'
    values:
      layout: sidenav
  - scope:
      path: 'content/_landing/*'
    values:
      layout: landing
  - scope:
      path: 'content/**/*/*._en.md'
    values:
      lang: en
  - scope:
      path: 'content/**/*/*._es.md'
    values:
      lang: es
  - scope:
      path: 'content/**/*/*._fr.md'
    values:
      lang: fr
  - scope:
      path: 'content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office.*.md'
    values:
      exclude: false

show_po_search: true