run: jekyll npm-watch-js

_config.dev.yml:
	touch _config.dev.yml

jekyll: _config.dev.yml
	bundle exec jekyll serve --watch --incremental --config _config.yml,_config.dev.yml

npm-watch-js:
	NODE_ENV=development npm run watch-js
