run: jekyll npm-watch

_config.dev.yml:
	touch _config.dev.yml

jekyll: _config.dev.yml
	bundle exec jekyll serve --watch --config _config.yml,_config.dev.yml

npm-watch: export NODE_ENV := development
npm-watch:
	npm run watch
