#!/usr/bin/env ruby

require 'csv'
require 'pry'
require 'yaml'

def insert_hash(hash, keys, insert)
  key = keys.shift
  if !hash.key?(key)
    hash[key] = Hash.new
  end
  if keys.length > 0
    insert_hash(hash[key], keys, insert)
  else
    hash[key] = insert
  end
end

csv = CSV.parse($stdin.read, headers: true)

es_hash = Hash.new

csv.each do |row|
  keys = row[0].split('.')

  insert = row[2]
    .gsub(/\]\s+\(/, '](') # Remove spaces between markdown link notation
    .gsub(/\)\s+\{/, '){') # Remove space between link and attributes
    .gsub(/(https)\s*\:\s*\/\//, 'https://') # Remove space between https://
    .gsub(/\{\s*\:\s*[t,T](arget)(.|\n)+?\}/, '{:target="_blank"}') # fix target formating

  insert_hash(es_hash, keys, insert)
end

puts es_hash.to_yaml

