#!/usr/bin/env ruby
# Run HTMLProofer via Ruby so we can do advanced things like
# ignore bad peer certificates which turn up in external links
require 'html-proofer'

directory = ARGV.first
if directory.nil?
  abort <<~STR
    Usage: #{$PROGRAM_NAME} DIRECTORY
  STR
end

# ignore new files from the PR
directories = %w(content)
merge_base = `git merge-base origin/production HEAD`.chomp
diffable_files = `git diff -z --name-only --diff-filter=AC #{merge_base}`.split("\0")
diffable_files = diffable_files.select do |filename|
  next true if directories.include?(File.dirname(filename))
  filename.end_with?('.md')
end.map { |f| Regexp.new(File.basename(f, File.extname(f))) }

HTMLProofer.check_directory(directory, {
  url_ignore: diffable_files,
  external_only: true,
  typhoeus: {
    ssl_verifypeer: false,
    ssl_verifyhost: 0,
  },
}).run
