#!/usr/bin/env ruby
# Run HTMLProofer via Ruby so we can do advanced things like
# ignore bad peer certificates which turn up in external links
require 'html-proofer'

directory = ARGV.first
if directory.nil?
  abort <<~STR
    Usage: #{$PROGRAM_NAME} DIRECTORY
  STR
end

HTMLProofer.check_directory(directory, {
  external_only: true,
  typhoeus: {
    ssl_verifypeer: false,
    ssl_verifyhost: 0,
  },
  url_ignore: [
    %r|https://help.cbp.gov|, # this site is down temporarily
  ]
}).run
